name: Node.js CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: easybook CI Discord Notification (success)
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.EASYBOOK_FRONT_WEBHOOK }}
          title: "✅ easybook-CI Success! ✅"
          status: ${{ job.status }}
          description: "ㅉㅆ 성공~"
          color: 65280
          url: "https://github.com/sarisia/actions-status-discord"
          username: "easybook-bot"

      - name: easybook CI Discord Notification (failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.EASYBOOK_FRONT_WEBHOOK }}
          title: "❗️ easybook-CI Fail! ❗️"
          status: ${{ job.status }}
          description: "실패 아으!@@"
          color: 16711680
          url: "https://github.com/sarisia/actions-status-discord"
          username: "easybook-bot"
